var MYIMG = {
  width : 176, height : 176, bpp : 4,
  buffer : require("heatshrink").decompress(atob("AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AFMBiEQIX4APiU//4ACAgnzkBM/U5BPEABUyKP4ADgRLF+czAAJXH+c/+RV/gCrMLQIODmZjDkJV8iZVNKIgAHiBW5l5OEe4L8EJQUyKQ0jAokgK270DVhUzkQCCAASxImJV0gJWLVoZUCWIIDBVgawFLGkBKpRWEVQZPBAghXBBIYHCmRXxKxxREKYQBBVYciW4IJBXoKxyn6rMfQZHCJoKuFBgYACCwZYul5WJ+f/mZaCKQcjmSsEKw66FmBWrj5WIn4ACWIieELIZMBXQZlEmQYDiBWpganDK4qfEmc/V4QCBVApYCVogOCLIJqDK1EBVpBdCKQIAHLQJUCVQSwEBQQUEAoRYoKxKvCWIydBfASnEKgJWCVIJXGCwUzmBWlj5XMV4z8FAgJbCKYRUHAAxWkgJWLAAXzLAxQCVIRXCUYQGBK5kyK8cvJok/KQhUCWQQ5DUwZaCAAarCBwJQFZg8wK0MDVRRcBGYKvFmT8ELAgOEAIQAEDgIIEWESoEAApTDSIIBBLIpYDfpgADPARYEmKuq+ZPEHYjrDKoKqBLQKnGAA50CCIsQK7z/G+YFDeAjtFMQUjmUyKwKySEgqweh5XGV4gyDJII6FJ4MjAAJXCYIpyDLBywdJ4pXE+ZXLVARVDBogXB/6zSWDkDKwg4CWYRPGfISOBAYIGBLIiZDOwJyEAB6wbVAaQCn5UGKwSwCUYaqFLwIAaWDSuFK4TtEIwMyKoKjCcoaoCVQgANYwQNKK7MfVwhaDAAqsDK4Q+CAgJWPmRxBDAbCKmBWXgM/K4QDBLAJcCLYilBG4SyDLoZlCCIRVIKgIdBkbRBNRZXXgZVE+YDBWA6vDIASuCS4zJJKARUDCwQKDWDqnCn4eCLYQAHUwajCKw5BBT5IJBWAIgDDIqwbVwM/+fzKYU/LgIBBTIpGFIAI8GfoQAMLAIRBCRcgK6kvK4TtNWpC2DMAYYOOQYaCmTFHmBXUf4P/K44HEXQQ8HHQJZEK6IXBDAbPHmZWTgZXCDggHBW4q2HRoUiH4Q7CK5vzDARXFOooACkCuVK4nzAwXzKY5aHkYBBHYSvOfwcyDAIWCOgM/CIkwK6RWGK4ZWBEwZFLSwIACkYRKI4pYFOIKwIKyMDK4SlFLAKtJF45XFeggAKM4RuFK4IZDGwUgK6E/f4YAE/6LIdIhXHHYRXPN4qvCWBEwKx8BVxE/L4fzLYcjcYJbHKghDDWBwXDEAJaCmQZCGYZXPgZXEDIRWBD4gAMGgKrGKxCCFLAZaCLgQGBDQ0QK50TK4QYELoJWNBoY5DK4jtGEoZwFVQRzEWIQqFmBXOFIJXFVwXzMAqtKHwRWCAoJeCNgxXEUQJOBOIhZFLAkxKxsBFIIqEGAc/AQJZFXAqPCIAQ3EYhItBDgRTDVooAFGAhXNh4oCbQqwCLIZSFAIRYDIQjDMbgkiZIJwDWJYABiBXMiYoBV4ahF+ZbBBAJnEJwJUCFwYIBKxgAGK4JWLFAI+DmBXMbASCEWIofBKYJnDdAYuBmSUBkZXLB4JWIZgZXJSwnyK5xIBfggECVwIABdIQJCbYbiKAAgQBMgJXHNoSvKkYkBG4U/KxcDVgRWELIhkCLYIDCVwY4CLQSZDJYxlKK4QANHwkQK5nzLJRTCVwIDCRgYDFVAhHBCQpNCMo5XSmcwK5UvIwJUFVgf/n4LCK46eEUAg1BT4JXGXw75BPAonHK6BGCI4ZYEKwQECM4jnJXYqvHXYSuLExAUE+RXKUgM/n4TDAgfzBYJkCXwivISBJFCIwJWGO5RXKmZWJgKeDLIJNBUoa6CAAJoCGoJXFIwRbHJIcjJgZWGOBB3JAAUQK5EDKQSsDVQJOCKw6vJGpShEJ4MzIIiuFEpZXEmBXJKwqyDXIRVCAALnNBAgRDUIwaCO5BXKV4vwK5EjIwZKFVwixDK5g7DGgQUBCI8jWYIQCV6sxK5BTDUQ3zVgM/WIJYD+aPEUAhBCOgqwFiQWFLYJSEV5awE+ZXJABBVB+ZVEAAIGBdAiYCUYROBEJA+CiJDEDQSpKLAwiEK6BVBVAYCEKoJXCFIyXBLgJXIJhJXNBgpXMgU/KIJWEJYKmBLgpaCCQbYFAwJXUJQy4BABQiEiBXGgYMDf4JKCf4YEBLwQADKIhLGWQIAIIhRYDCBYmGmBXLfAk/KoYLCV4ZYFABDIBV550BUIoRLBgJXPJAI5BKwJfDVwy6CK6ZCGiT/BIgQHBaARXJBoUyCARXHiY4IUQhdCKogMBLBhXJHQIDBkJYBToQLDkZXJMgYDCmJXGBQRWCn5dGA4X/XgIACKiRWDIwIFBkYGBiIIDAQI7CKxISBMwRbCK4wxFJ4KeEAgRSBn5YCViZEFmRYDV4JfCI4L5CKIazHK4kzK48TKAigCLYQCCKYSvFWSI/EAwQHDLwIBBIoavICQQPBDoRXITwJSCAYRXCKQIACVoIIBB4KwTTgg6BT4oREBQRZJM4RXLbAQAGfohRCKaYAEHwr2HVprCDYIhXGBQYAHWoYAbKIRfKB4QQCYAKvIAIRNCiBWEgJTQVoxjRR4Y8DK5IICKwYVDAoRlBMwITCK4sCIAKxIBAs/LAxMIJwgAFR4TuBT44uCAgROFX4wEDkBXEgYdBHQgANLRg/DM5JIBe5BXEJYICCXwwLCK48BCoJFHJhgAaIYMhLAy7CMoRXEIwRXNXYUjkINBiY2In4GGMxTRNK5BWBXZBhDXwhXHgUyI4LaBCoY8DCwQALBwgTOHgRMKBpAIBFAIHEV48xRop6BJJKnOVpIJEHgURJYqPBLQZYHDIg/CmBXEgcTJgYPDAB5ECmRtGChRHDkMRLAwAHMAItDBIivHgAoBkYsBCwYSBXQKcLIwiHFLos/SQquCK4USK5i2CXAyvHgAJBmIPDiUxKIJ2CAByJCCYR3CCRSvDKowGENYoFFMAJXHgITDWIIXDZgZZNeoZTDD4LJKK4a0DWwZgDJYQCBIIS6GmUgV4sRmTFCYwQYCLAQWBLYoIBIg4FEMowFEU4gnBK4sRkJZCGIPyKoxYDK40SiEDQAIVJkUTLwT8BK4xuBKQoAGW4aYFE4MSWoKwGSYSuIBgRXGgEQmLMEFoi6DV4TCCLIYLBAAQGBBYTpEYRBRBFgZWEBIRaEABRXHgMCbIZYFOwQCBIAR/CKoKeDA4JXCdIS2CBgRWFK4L8DAoMSVwa1DBoIVDAA8QK44MDOYqoCEIT9CL4RcCfIZvBKYQFBVYjNCNARSDUgIxBV4pXDXwgAIVxEgiKxDAASzDS4QEDXggGCIILACLIRpBNoRsDK4gWBJ4KpEAAhhBdIoADBQRXGLITWDWAYqBHIZSEEopQCOAoPBOYQCFAApUBV4xZFKYpfDIYJWHiEAgUSkZRCKwhQFII5PCYQ8ykYUHXQLFCVhAAFGohpCIQURV5MQmKvDiREDHIYDCJ4gEB+RFDVYRfFBIQAIFwJZLV4qwCiIVBUwJXIiMBAQIbHAAZmBJATBDWAqqBWIYEBkKuEAAQaCFoKuLHYQbDBYhWILAcQDQIcDFoRbHTYypFAoRTHLAsSiUvK5xrBiTBFK5UQiASCKQJaBJBYFDAwQIEmaxCmZUKdwKcGAAwXECgIKDiBXKWAMCCIUhFgIyBSRCvGBo5ZBCIxTBUIqcFK5AOBCAxXMWIJXDDQaUIVYIIFiczJ4qvEPQJJHBJJXEBoK/GKxpYCgMRgIaDWAi5CABYTBKYMjmc/dQiuGABxkJKhoCBKwKyDAAUgI4YAHM4wADka2BAII+IFwIAUVp4ACFQKzCHAarEiMyKJLADCAJYBZAhPVVhEBLKKCCWQLmCJ4MRgRHDiUjmJaCJAJfEAwyTEAII9BVs4ACgQsBRokhiQGCJAMSV5MxAQIMFVozbBAQRaSKygABkUBFoK0CVIQ/CKwaxBW4IAHBIIQCTBAABWgQMHKg6uVCoTfGiS0DIwUSmUigRRCAoMjAoQSDK4YhEFwQqBK4YDBXYUBBIcQgSuXFYQkCAAivBT4IABLIRJBVIRcBBQLBCZARJEK44sBWgRMFLwatVAAyrCLYgoBiUSgL4EAgRaCAAJxGHwYDBAgKCBcASyBdxQLKABwyDH4MhgESBISXFK4JeBCAMxMAhXJIIJDEUA4pBKYZWZLgzlCdoysCMwJYCAAMhAgYAEEgz0LKwIVBgJWfFApWBgKyCfZERiavGFyosBKkQnDcQQEBkESWgz9EAYbuDbRguGiRWkAAZRDAYK2CJ4Q4CLg4nQDwIDCiQXRKy4DDkRTCGIJhCVYchK4bYSD4JUoWhZSBG4I8CXoivRPwJqQWckQiC4DBgxXDIxoPBNASuqJggEDKwJIGKwgMBBw4AHKYZXqGgwxEJJBVCMwMhUQJVNQYpYuYhpWBMYRdBT5yuwJowJSAH6POLAhdQYoJf9KAxF+AH4AviJA/ABr9/AH4AyiKz/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AH4A/AD4"))
};

//var IMAGEWIDTH = 176;
//var IMAGEHEIGHT = 109;
//var IMAGEWIDTH = 176;
var IMAGEHEIGHT = 176;

Graphics.prototype.setFontMichroma36 = function() {
g.setFontCustom(atob("AAAAAAAAAAAAAAAAeAAAAAeAAAAAeAAAAAeAAAAAAAAAAAAAAAAAAAAAAAGAAAAA+AAAAD+AAAAP+AAAA/8AAAD/wAAAf/AAAB/4AAAH/gAAAf+AAAB/4AAAH/gAAAf+AAAAfwAAAAfAAAAAcAAAAAAAAAAAAAAAAAAAAAAAA///AAD///wAH///4AP///8APwAD+APAAAeAeAAAeAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAPAeAAAeAPAAAeAPwAD+AP///8AH///4AD///wAA///AAAAAAAAAAAAAAAAAAAAAEAAAAAOAAAAAfAAAAA+AAAAB8AAAAD8AAAAH4AAAAPwAAAAPgAAAAfAAAAAf///+Af///+Af///+Af///+AAAAAAAAAAAAAAAAAAAAAAAAAA/Af+AD/A/+AH/B/+AP/D/+APwD4eAPADweAfADweAeADweAeADweAeADweAeAHgeAeAHgeAeAHgeAeAHgeAeAHgeAeAHgeAeAHgeAeAHgeAeAHgeAeAHgeAeAPgeAeAPAeAeAPAeAeAPAeAeAPAeAfAPAeAPw/AeAP/+AeAH/+AeAD/8AeAB/wAOAAAAAAAAAAAAAAAAAAAAAAAAAB8APgAD8AP4AH8AP8AP8AP8APgAB+AfAAAeAeAAAeAeAAAPAeAAAPAeAAAPAeAAAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAPAeAeAeAfAeAeAPx/h+AP///+AH///8AD///4AB/h/gAAAAAAAAAAAAAAAAAAAAAAeAAAAA/AAAAA/AAAAB/AAAAD/AAAAH/AAAAPvAAAAPPAAAAfPAAAA+PAAAB8PAAAD4PAAADwPAAAHwPAAAPgPAAAfAPAAA+APAAA8APAAB8APAAD4APAAHwAPAAPgAPAAPAAPAAfAAPAAf///+Af///+Af///+Af///+AAAAPAAAAAPAAAAAPAAAAAPAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAf/8PgAf/8P4Af/8P8Af/8P8AeB4A+AeB4AeAeDwAeAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAPAeDwAfAeDwAeAeD4A+AeD+D+AeB//8AeB//4AeA//4AAAP/AAAAAAAAAAAAAAAAAAAAAAAAAAA///AAD///wAH///4AH///8AP4fB+APAeAeAfA8AeAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAfA8APAPA+AeAPgeAeAP8fh+AH8f/8AD8P/8AA8H/4AAAB/gAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAeAAAAAeAAAAAeAAAAAeAAAAAeAAACAeAAAGAeAAAOAeAAAeAeAAA+AeAAD+AeAAH8AeAAP4AeAAfwAeAA/gAeAB/AAeAD+AAeAP4AAeAfwAAeA/gAAeB/AAAeD+AAAeH8AAAefwAAAe/gAAAf/AAAAf+AAAAf8AAAAf4AAAAfgAAAAfAAAAAAAAAAAAAAAAAAAAAAAAAAMAAB+B/wAD/j/4AH/3/8AP///+AP//A+AfB+AeAeA+AeAeA+APAeA+APAeA+APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA8APAeA+APAeA+APAeA+APAeA+AOAeA+AeAPh/A+AP///+AP/3/8AH/3/8AB/D/wAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAD/4HAAH/8HwAP/+H4AP5/H8AfAfA8AeAPAeAeAPAeAeAPAeAeAHgfAeAHgPAeAHgPAeAHgPAeAHgPAeAHgPAeAHgPAeAHgPAeAHgPAeAHgPAeAHgPAeAHgPAeAHgPAeAHAPAeAPAOAeAPAeAPAPAeAPwfB+AP///8AH///4AD///wAA///AAAAAAAAAAAAAAAAAAAAAAAAAAAB8DwAAB8HwAAB8HwAAB8DwAAAAAAAAAAAAA"), 46, atob("CBIkESMjJCMjIyMjCA=="), 36+(1<<8)+(1<<16));
};

// timeout used to update every minute
var drawTimeout;

// schedule a draw for the next minute
function queueDraw() {
  if (drawTimeout) clearTimeout(drawTimeout);
  drawTimeout = setTimeout(function() {
    drawTimeout = undefined;
    draw();
  }, 60000 - (Date.now() % 60000));
}


function draw() {
  //clock pos
  var x = g.getWidth()/2;
  var y = 105;
  g.setColor("#000000"); //color of clock text
  //draw clock
  g.drawImage(MYIMG,0,g.getHeight()-IMAGEHEIGHT, 1);
  //get time/date
  var date = new Date();
  var timeStr = require("locale").time(date,1);
  var dateStr = require("locale").date(date).toUpperCase();
  var dowStr = require("locale").dow(date).toUpperCase();
  // draw time
  g.setFontAlign(0,0).setFont("custom");
  g.drawString(timeStr,x,y);
  // draw date
  g.setColor(1,1,1);
  var dateFormatted = dowStr + ", " + dateStr;
  g.setFont("6x8");
  g.drawString(dateFormatted,g.getWidth()/2,g.getHeight() - 8);
  Bangle.drawWidgets();
  // queue draw in one minute
  queueDraw();
}


g.setTheme({bg:"#000",fg:"#fff",dark:true}).clear();
draw();
Bangle.on('lcdPower',on=>{
  if (on) {
    draw();
  } else {
    if (drawTimeout) clearTimeout(drawTimeout);
    drawTimeout = undefined;
  }
});
Bangle.setUI("clock");
Bangle.loadWidgets();
Bangle.drawWidgets();
